### ISSUE TITLE
Tracks being summed up to mono on receive

### ISSUE THREAD

**Issue by MrKleiner** [tin2tin/audacity_tools_for_blender#1]
Hello, thank you for such an awesome addon :D I like it very much even though I usually use Audition :D 

It appears that tracks are being summed to mono for some reason. Is this a bug or feature?

- Strip sending works just fine and everything is stereo as it should be.
![image](https://user-images.githubusercontent.com/37084600/110188983-5ed7f380-7e26-11eb-894b-3b90d4ea1803.png)

- But after clicking "receive" and then "send" again - strip appears to be mono.
![image](https://user-images.githubusercontent.com/37084600/110189110-afe7e780-7e26-11eb-954c-4fa8ca3a19be.png)

**Comment by tin2tin** [comment]
I don't know much about Audacity or working with audio. If you feel up for some tweaking, a place to look at is the  do_command ex. here: https://github.com/tin2tin/audacity_tools_for_blender/blob/main/__init__.py#L478 These commands are the ones remote controlling Audacity. Here are all of them: https://manual.audacityteam.org/man/scripting_reference.html 

In that specific line I send you a link to there is: `NumChannels=1.0` if you change that to 2.0 does it become stereo then? 

Currently, I don't know about getting info from Audacity to Blender, ex. in this case you would need to know if a clip is stereo or mono, before doing the export of the file. 

If you want to tweak it, then paste the contents of `__init__.py` into the Blender text editor, do the tweak and run it, but you'll need to close Blender each time before running the code or there will be an error.

**Comment by tin2tin** [comment]
I think I've solved it.

**Comment by MrKleiner** [comment]
Yes. The issue is fixed! everything works fine :D Thank you !
![image](https://user-images.githubusercontent.com/37084600/110205643-e0a93a80-7e81-11eb-84cb-4e11c29369be.png)
