### ISSUE TITLE
empty track when sending sequence or selection to audacity

### ISSUE THREAD

**Issue by samytichadou** [tin2tin/audacity_tools_for_blender#17]
when sending from blender to audacity in sequence or selection mode, audacity seems to have an extra empty track (under the others)

From 
![image](https://user-images.githubusercontent.com/26276003/111325102-a99a0c80-866b-11eb-82d8-9c15f01b569b.png)

To 
![image](https://user-images.githubusercontent.com/26276003/111325163-b7e82880-866b-11eb-9a75-572b0cd34cd5.png)

**Comment by tin2tin** [comment]
Should be fixed with this patch: https://github.com/tin2tin/audacity_tools_for_blender/commit/27e8ae9730804279dd95d284f80e8726ab36bfd6
