### ISSUE TITLE
mod_script_pipe on Audacity wiki says available in windows and macOS (no Linux?)

### ISSUE THREAD

**Issue by luzpaz** [tin2tin/audacity_tools_for_blender#2]
Or am I misunderstanding?  
https://manual.audacityteam.org/man/scripting.html

**Comment by tin2tin** [comment]
I don't have Linux myself, but I know the Steve from the Audacity community is running Linux and mod_script_pipe is working for him. 

Where does it fail if you try to use Audacity Tools for Blender?

**Comment by luzpaz** [comment]
haven't tried it yet. was just trying to figure out the what the prerequisites were before doing so.

**Comment by pistolario** [comment]
Hello,
  In Linux Mint, the module mod_script_pipe is missing. But if you use the PPA source of packages linked by Audacity web: https://launchpad.net/~ubuntuhandbook1/+archive/ubuntu/audacity
It has the module

**Comment by tin2tin** [comment]
As it seems like it is working om Linux(in general?) I'll close thia add-on for now.
