### ISSUE TITLE
Receive result strip second time

### ISSUE THREAD

**Issue by pistolario** [tin2tin/audacity_tools_for_blender#4]
The first time you push "receive" it renders the audio in Audacity and imports it as a strip. But the next time, it does the same and creates a new strip. 
Perhaps, only force update file of strip in Blender?

**Comment by tin2tin** [comment]
There is no way to detect what has been done previously, and replacing stuff in Blender, may delete stuff, which shouldn't be deleted. So the "clean-up" needs to be manual.
