### ISSUE TITLE
explanatory gif too heavy

### ISSUE THREAD

**Issue by samytichadou** [tin2tin/audacity_tools_for_blender#5]
Just a little thing, the explanatory gif hosted in this repo is quite heavy, i just cloned the repo to test the addon and waited 15mb download, no big deal but pasting url from giphy for example would be more efficient
Cheers !

**Comment by tin2tin** [comment]
Haha, yeah I know, giphy can't take files that size. I just finished a new tutorial on Youtube, I'll replace it with that.
https://youtu.be/f61Zvb8AipA
